# Generated by Django 2.0 on 2018-01-01 04:08

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20171231_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Type',
            field=models.CharField(choices=[('C', 'Computer'), ('M', 'Math'), ('E', 'English')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='update_date'),
        ),
    ]
