# Generated by Django 2.0 on 2018-01-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180101_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Type',
            field=models.CharField(choices=[('C', 'Computers'), ('M', 'Math'), ('E', 'English')], max_length=1),
        ),
    ]
