# Generated by Django 2.0 on 2017-12-30 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='face',
        ),
        migrations.RemoveField(
            model_name='account',
            name='permission',
        ),
    ]
