# Generated by Django 2.0 on 2017-12-29 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_order', models.IntegerField(verbose_name='章节编号')),
                ('title', models.CharField(max_length=50, verbose_name='章节标题')),
                ('description', models.TextField(verbose_name='章节介绍')),
            ],
            options={
                'db_table': 'ChapterList',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50, verbose_name='大学')),
                ('course_order', models.IntegerField(verbose_name='课程编号')),
                ('course_identifier', models.CharField(max_length=50, verbose_name='课程号')),
                ('title', models.CharField(max_length=50, verbose_name='课程名称')),
                ('image', models.ImageField(default='../static/images/HighPerformance.png', height_field=650, upload_to='', width_field=1150)),
                ('description', models.TextField(verbose_name='课程介绍')),
                ('teacher', models.CharField(max_length=50, verbose_name='授课老师')),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='PPTList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_order', models.IntegerField(verbose_name='PPT编号')),
                ('title', models.CharField(max_length=50, verbose_name='PPT标题')),
                ('path', models.CharField(max_length=100, verbose_name='PPT路径')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LemonApp.ChapterList')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LemonApp.Course')),
            ],
            options={
                'db_table': 'PPTList',
            },
        ),
        migrations.AddField(
            model_name='chapterlist',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LemonApp.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='pptlist',
            unique_together={('id', 'course_id', 'chapter_id')},
        ),
        migrations.AlterUniqueTogether(
            name='chapterlist',
            unique_together={('id', 'course_id')},
        ),
    ]
