# Generated by Django 2.0 on 2018-01-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pptimage',
            name='image',
        ),
        migrations.AddField(
            model_name='pptlist',
            name='image',
            field=models.FilePathField(default='/PPT', path='C:\\Users\\M4298\\Documents\\db_project\\new\\LEMONTEA\\LemonApp/media/PPT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pptlist',
            name='page_count',
            field=models.IntegerField(default=0, verbose_name='页数'),
            preserve_default=False,
        ),
    ]
