# Generated by Django 2.0 on 2017-12-31 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_order', models.IntegerField(verbose_name='评论顺序')),
                ('content', models.TextField(verbose_name='评论内容')),
            ],
            options={
                'db_table': 'CourseComment',
            },
        ),
        migrations.CreateModel(
            name='PPTComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_order', models.IntegerField(verbose_name='评论顺序')),
                ('content', models.TextField(verbose_name='评论内容')),
            ],
            options={
                'db_table': 'PPTComment',
            },
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=50, verbose_name='学号')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LemonApp.College')),
            ],
            options={
                'db_table': 'StudentInformation',
            },
        ),
        migrations.CreateModel(
            name='TeacherInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherID', models.CharField(max_length=50, verbose_name='教工号')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LemonApp.College')),
            ],
            options={
                'db_table': 'TeacherInformation',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='college_id',
            field=models.IntegerField(default=-1, verbose_name='所属大学'),
        ),
        migrations.AddField(
            model_name='pptcomment',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pptcomment',
            name='ppt_image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LemonApp.PPTImage'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='couse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LemonApp.Course'),
        ),
    ]
