# Generated by Django 2.0 on 2017-12-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pptimage',
            unique_together={('id', 'ppt_id')},
        ),
        migrations.AlterModelTable(
            name='pptimage',
            table='PPTImage',
        ),
    ]
