# Generated by Django 2.0 on 2017-12-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0002_auto_20171229_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(height_field=650, upload_to='', width_field=1150),
        ),
    ]
