# Generated by Django 2.0 on 2018-01-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0002_auto_20180102_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pptlist',
            name='page_count',
            field=models.IntegerField(null=True, verbose_name='页数'),
        ),
    ]
