# Generated by Django 2.0 on 2017-12-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0002_auto_20171230_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='face',
            field=models.ImageField(default='UserPhoto/default.png', null=True, upload_to='UserPhoto/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='account',
            name='permission',
            field=models.IntegerField(null=True, verbose_name='权限类型'),
        ),
    ]
