# Generated by Django 2.0 on 2017-12-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0003_auto_20171229_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
