# Generated by Django 2.0 on 2018-01-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0003_auto_20180102_1548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pptimage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pptimage',
            name='ppt_id',
        ),
        migrations.RemoveField(
            model_name='pptcomment',
            name='ppt_image_id',
        ),
        migrations.RemoveField(
            model_name='pptlist',
            name='image',
        ),
        migrations.AddField(
            model_name='pptcomment',
            name='page_num',
            field=models.IntegerField(default=0, verbose_name='页数'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PPTImage',
        ),
    ]
