# Generated by Django 2.0 on 2018-01-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0003_account_idcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='IDcard',
            new_name='card_number',
        ),
    ]
