# Generated by Django 2.0 on 2018-01-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0004_auto_20180102_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='pptcomment',
            name='ppt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LemonApp.PPTList'),
            preserve_default=False,
        ),
    ]
