# Generated by Django 2.0 on 2018-01-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0004_auto_20180101_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='is_bind',
            field=models.BooleanField(default=False, verbose_name='是否被绑定'),
        ),
        migrations.AddField(
            model_name='teacherinformation',
            name='is_bind',
            field=models.BooleanField(default=False, verbose_name='是否被绑定'),
        ),
        migrations.AlterUniqueTogether(
            name='studentinformation',
            unique_together={('college_id', 'StudentID')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherinformation',
            unique_together={('college_id', 'TeacherID')},
        ),
    ]
