# Generated by Django 2.0 on 2017-12-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0004_auto_20171229_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='college_name',
            field=models.CharField(max_length=50, null=True, verbose_name='大学'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_order',
            field=models.IntegerField(null=True, verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
