# Generated by Django 2.0 on 2017-12-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0005_auto_20171229_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='CoursePhoto/'),
        ),
    ]
