# Generated by Django 2.0 on 2018-01-01 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0005_auto_20180101_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
