# Generated by Django 2.0 on 2017-12-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0006_auto_20171229_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='CoursePhoto/HighPerformance.png', height_field=650, null=True, upload_to='CoursePhoto/', width_field=1150),
        ),
    ]
