# Generated by Django 2.0 on 2017-12-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0009_auto_20171229_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='CoursePhoto/HighPerformance.png', null=True, upload_to='CoursePhoto/'),
        ),
    ]
