# Generated by Django 2.0 on 2017-12-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LemonApp', '0010_auto_20171229_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='CoursePhoto/default.png', null=True, upload_to='CoursePhoto/'),
        ),
    ]
